"""people directory and role holders

Revision ID: 0022cbf0dbd7
Revises: 160ce9527914
Create Date: 2026-09-07 01:10:39.557729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0022cbf0dbd7'
down_revision: Union[str, Sequence[str], None] = '160ce9527914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('project_roles', sa.Column('person_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'project_roles', 'people', ['person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_roles', type_='foreignkey')
    op.drop_column('project_roles', 'person_id')
    op.drop_table('people')
    # ### end Alembic commands ###
