"""user stories, acceptance criteria, test cases

Revision ID: 0b3aa2df468a
Revises: 5faa3386275c
Create Date: 2026-09-05 17:45:25.254235

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0b3aa2df468a'
down_revision: Union[str, Sequence[str], None] = '5faa3386275c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=True),
    sa.Column('story_key', sa.String(length=32), nullable=False),
    sa.Column('team', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('capability', sa.Text(), nullable=False),
    sa.Column('benefit', sa.Text(), nullable=False, server_default=''),
    sa.Column('source_status', sa.String(length=16), nullable=False, server_default='inferred'),
    sa.Column('source_chunk_keys', sa.Text(), nullable=False, server_default=''),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['project_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stories_team'), 'user_stories', ['team'], unique=False)
    op.create_table('acceptance_criteria',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_story_id', sa.String(length=36), nullable=False),
    sa.Column('criterion_key', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_story_id'], ['user_stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_story_id', sa.String(length=36), nullable=True),
    sa.Column('case_key', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('preconditions', sa.Text(), nullable=False, server_default=''),
    sa.Column('action', sa.Text(), nullable=False, server_default=''),
    sa.Column('expected_result', sa.Text(), nullable=False, server_default=''),
    sa.Column('kind', sa.String(length=32), nullable=False, server_default='functional'),
    sa.Column('rests_on_assumption', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('assumed_fields', sa.Text(), nullable=False, server_default=''),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_story_id'], ['user_stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_cases')
    op.drop_table('acceptance_criteria')
    op.drop_index(op.f('ix_user_stories_team'), table_name='user_stories')
    op.drop_table('user_stories')
    # ### end Alembic commands ###
