"""board drift and card fingerprint

Revision ID: 160ce9527914
Revises: d31f0a7c58e2
Create Date: 2026-09-07 00:13:30.221332

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '160ce9527914'
down_revision: Union[str, Sequence[str], None] = 'd31f0a7c58e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_drift',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default, because project_tasks already holds rows and a NOT NULL
    # column cannot be added to them without one. An empty fingerprint reads
    # as 'never written to a board', which is true of every existing row.
    op.add_column(
        'project_tasks',
        sa.Column('board_fingerprint', sa.String(length=64), nullable=False, server_default=''),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_tasks', 'board_fingerprint')
    op.drop_table('board_drift')
    # ### end Alembic commands ###
