"""task estimate source

Revision ID: 48d51090a6d2
Revises: 0b3aa2df468a
Create Date: 2026-09-06 02:10:31.219282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d51090a6d2'
down_revision: Union[str, Sequence[str], None] = '0b3aa2df468a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'project_tasks',
        # Existing rows were scheduled on the default, which is what
        # 'assumed' means, so backfilling them with it is accurate.
        sa.Column('estimate_source', sa.String(length=16), nullable=False, server_default='assumed'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_tasks', 'estimate_source')
    # ### end Alembic commands ###
