"""initial schema

Revision ID: 4d884281e90f
Revises: 
Create Date: 2026-09-05 00:52:14.087958

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4d884281e90f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assumptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('assumption_key', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('graph_node', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_requests_input_hash'), 'llm_requests', ['input_hash'], unique=False)
    op.create_table('sow_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('doc_key', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('parsing_status', sa.String(length=32), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sow_sections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sow_document_id', sa.String(length=36), nullable=False),
    sa.Column('section_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sow_document_id'], ['sow_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('team', sa.String(length=32), nullable=False),
    sa.Column('assignee', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('source_status', sa.String(length=16), nullable=False),
    sa.Column('source_sow_section_id', sa.String(length=36), nullable=True),
    sa.Column('source_chunk_keys', sa.Text(), nullable=False),
    sa.Column('grounding_score', sa.Float(), nullable=True),
    sa.Column('validation_status', sa.String(length=32), nullable=False),
    sa.Column('external_ref', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_sow_section_id'], ['sow_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sow_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_key', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sow_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sow_chunks_chunk_key'), 'sow_chunks', ['chunk_key'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('depends_on_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['project_tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'depends_on_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_dependencies')
    op.drop_index(op.f('ix_sow_chunks_chunk_key'), table_name='sow_chunks')
    op.drop_table('sow_chunks')
    op.drop_table('project_tasks')
    op.drop_table('sow_sections')
    op.drop_table('sow_documents')
    op.drop_index(op.f('ix_llm_requests_input_hash'), table_name='llm_requests')
    op.drop_table('llm_requests')
    op.drop_table('assumptions')
    op.drop_table('projects')
    # ### end Alembic commands ###
