"""clarification questions

Revision ID: 5faa3386275c
Revises: bf61dfc5d149
Create Date: 2026-09-05 17:40:05.453053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5faa3386275c'
down_revision: Union[str, Sequence[str], None] = 'bf61dfc5d149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clarification_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('question_key', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('team', sa.String(length=32), nullable=False, server_default=''),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('working_assumption', sa.Text(), nullable=False, server_default=''),
    sa.Column('status', sa.String(length=16), nullable=False, server_default='open'),
    sa.Column('answer', sa.Text(), nullable=False, server_default=''),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clarification_questions_scope'), 'clarification_questions', ['scope'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clarification_questions_scope'), table_name='clarification_questions')
    op.drop_table('clarification_questions')
    # ### end Alembic commands ###
