"""requirements, roles, task role assignment

Revision ID: 88b4d7b79c04
Revises: a1135bee754f
Create Date: 2026-09-05 17:14:17.309753

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '88b4d7b79c04'
down_revision: Union[str, Sequence[str], None] = 'a1135bee754f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('team', sa.String(length=32), nullable=False),
    sa.Column('role_title', sa.String(length=64), nullable=False),
    sa.Column('responsibility', sa.Text(), nullable=False, server_default=''),
    sa.Column('headcount', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('source_status', sa.String(length=16), nullable=False, server_default='assumed'),
    sa.Column('source_chunk_keys', sa.Text(), nullable=False, server_default=''),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_key', sa.String(length=32), nullable=False),
    sa.Column('team', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False, server_default=''),
    sa.Column('source_status', sa.String(length=16), nullable=False, server_default='assumed'),
    sa.Column('source_sow_section_id', sa.String(length=36), nullable=True),
    sa.Column('source_chunk_keys', sa.Text(), nullable=False, server_default=''),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_sow_section_id'], ['sow_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'project_tasks',
        # project_tasks is populated, so NOT NULL needs a server_default or the
        # migration fails on every existing row.
        sa.Column('assignee_role', sa.String(length=64), nullable=False, server_default=''),
    )
    op.add_column('project_tasks', sa.Column('requirement_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'project_tasks', 'project_requirements', ['requirement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_tasks', type_='foreignkey')
    op.drop_column('project_tasks', 'requirement_id')
    op.drop_column('project_tasks', 'assignee_role')
    op.drop_table('project_requirements')
    op.drop_table('project_roles')
    # ### end Alembic commands ###
