"""sow milestones

Revision ID: 88c1872f1b5f
Revises: 48d51090a6d2
Create Date: 2026-09-06 02:35:10.366138

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '88c1872f1b5f'
down_revision: Union[str, Sequence[str], None] = '48d51090a6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_milestones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('source_status', sa.String(length=16), nullable=False, server_default='explicit'),
    sa.Column('source_chunk_keys', sa.Text(), nullable=False, server_default=''),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestone_tasks',
    sa.Column('milestone_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['project_milestones.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.id'], ),
    sa.PrimaryKeyConstraint('milestone_id', 'task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('milestone_tasks')
    op.drop_table('project_milestones')
    # ### end Alembic commands ###
