"""store SOW dates and merchant on project

Revision ID: 8d435b6d3c60
Revises: 4d884281e90f
Create Date: 2026-09-05 02:59:29.538169

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8d435b6d3c60'
down_revision: Union[str, Sequence[str], None] = '4d884281e90f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required: existing rows need a value for a NOT NULL column.
    op.add_column(
        'projects',
        sa.Column('merchant_name', sa.String(length=255), nullable=False, server_default=''),
    )
    op.add_column('projects', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('go_live_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'go_live_date')
    op.drop_column('projects', 'start_date')
    op.drop_column('projects', 'merchant_name')
    # ### end Alembic commands ###
