"""task review state

Revision ID: a1135bee754f
Revises: 9670469f4478
Create Date: 2026-09-05 04:06:53.617541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1135bee754f'
down_revision: Union[str, Sequence[str], None] = '9670469f4478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required: existing rows need a value for a NOT NULL column.
    op.add_column(
        'project_tasks',
        sa.Column('review_status', sa.String(length=16), nullable=False, server_default='pending'),
    )
    op.add_column(
        'project_tasks',
        sa.Column('review_note', sa.Text(), nullable=False, server_default=''),
    )
    op.add_column(
        'project_tasks',
        sa.Column('regeneration_count', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_tasks', 'regeneration_count')
    op.drop_column('project_tasks', 'review_note')
    op.drop_column('project_tasks', 'review_status')
    # ### end Alembic commands ###
