"""project detail items

Revision ID: bf61dfc5d149
Revises: 88b4d7b79c04
Create Date: 2026-09-05 17:33:21.992311

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bf61dfc5d149'
down_revision: Union[str, Sequence[str], None] = '88b4d7b79c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_details',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('team', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False, server_default=''),
    sa.Column('source_status', sa.String(length=16), nullable=False, server_default='explicit'),
    sa.Column('source_chunk_keys', sa.Text(), nullable=False, server_default=''),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_details_category'), 'project_details', ['category'], unique=False)
    op.create_index(op.f('ix_project_details_team'), 'project_details', ['team'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_details_team'), table_name='project_details')
    op.drop_index(op.f('ix_project_details_category'), table_name='project_details')
    op.drop_table('project_details')
    # ### end Alembic commands ###
