"""user story actor side

Revision ID: c9de6fd2d5e6
Revises: 88c1872f1b5f
Create Date: 2026-09-06 02:48:46.473488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9de6fd2d5e6'
down_revision: Union[str, Sequence[str], None] = '88c1872f1b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user_stories',
        sa.Column('actor_is_delivery_side', sa.Boolean(), nullable=False, server_default='false'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stories', 'actor_is_delivery_side')
    # ### end Alembic commands ###
