"""what each person can be put on

Revision ID: f601e4e5ea1d
Revises: 0022cbf0dbd7
Create Date: 2026-09-07 01:36:22.150987

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f601e4e5ea1d'
down_revision: Union[str, Sequence[str], None] = '0022cbf0dbd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_roles',
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('role_title', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'role_title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_roles')
    # ### end Alembic commands ###
